# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Принят'), (1, 'Оплачен'), (2, 'Исполнен'), (3, 'Отменен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Москва'), (1, 'Санкт-Петербург')], verbose_name='Город'),
        ),
    ]
