# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170731_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ресторана'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('name', 'city')]),
        ),
    ]
