# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170731_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSubcategory',
            fields=[
                ('dishcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.DishCategory')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
            bases=('orders.dishcategory',),
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='orders.DishCategory'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Dish Name'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Accepted'), (1, 'Paid'), (2, 'Completed'), (3, 'Cancelled')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(editable=False, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Moscow'), (1, 'Saint Petersburg')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Restaurant Name'),
        ),
        migrations.AddField(
            model_name='dishsubcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='orders.DishCategory'),
        ),
    ]
