# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170731_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishsubcategory',
            name='dishcategory_ptr',
        ),
        migrations.RemoveField(
            model_name='dishsubcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='orders.DishCategory'),
        ),
        migrations.DeleteModel(
            name='DishSubcategory',
        ),
    ]
